package waf

import (
	"crypto/tls"
	"fmt"
	"io"
	"net/http"
	"strings"
	"time"
)

const (
	RST = "\033[0m"
	R   = "\033[91m"
	G   = "\033[92m"
	Y   = "\033[93m"
	M   = "\033[95m"
	C   = "\033[96m"
	W   = "\033[97m"
	DIM = "\033[2m"
	BLD = "\033[1m"
)

// Result holds WAF detection result
type Result struct {
	Detected bool
	Name     string
	Evidence []string
}

// wafSignature defines a WAF fingerprint
type wafSignature struct {
	Name    string
	Headers map[string]string // header name -> contains value
	Body    []string          // body contains
	Cookies []string          // cookie name contains
	Status  []int             // specific status codes on attack
}

var signatures = []wafSignature{
	{
		Name: "Cloudflare",
		Headers: map[string]string{
			"cf-ray":              "",
			"cf-cache-status":     "",
			"server":              "cloudflare",
			"cf-mitigated":        "",
		},
		Body:    []string{"cloudflare", "cf-ray", "Attention Required! | Cloudflare", "__cf_bm"},
		Cookies: []string{"__cfduid", "__cf_bm", "cf_clearance"},
	},
	{
		Name: "AWS WAF / CloudFront",
		Headers: map[string]string{
			"x-amz-cf-id":       "",
			"x-amzn-requestid":  "",
			"x-amz-cf-pop":      "",
			"x-cache":           "cloudfront",
		},
		Body:    []string{"AWS WAF", "Request blocked", "x-amz-cf-id"},
		Cookies: []string{"aws-waf-token"},
	},
	{
		Name: "Akamai",
		Headers: map[string]string{
			"x-akamai-transformed": "",
			"akamai-origin-hop":    "",
			"x-check-cacheable":    "",
			"x-akamai-request-id":  "",
		},
		Body:    []string{"AkamaiGHost", "Akamai", "Reference&#32;&#35;"},
		Cookies: []string{"ak_bmsc", "bm_sz", "bm_sv"},
	},
	{
		Name: "Sucuri",
		Headers: map[string]string{
			"x-sucuri-id":      "",
			"x-sucuri-cache":   "",
			"server":           "sucuri/cloudproxy",
		},
		Body:    []string{"Sucuri WebSite Firewall", "sucuri", "Access Denied - Sucuri"},
		Cookies: []string{"sucuri_cloudproxy_uuid"},
	},
	{
		Name: "Imperva / Incapsula",
		Headers: map[string]string{
			"x-iinfo":         "",
			"x-cdn":           "incapsula",
		},
		Body:    []string{"incapsula incident id", "Incapsula", "_Incapsula_Resource", "Request unsuccessful. Incapsula"},
		Cookies: []string{"incap_ses", "visid_incap", "nlbi_"},
	},
	{
		Name: "ModSecurity",
		Headers: map[string]string{
			"server": "mod_security",
			"x-mod-security-message": "",
		},
		Body:    []string{"ModSecurity", "mod_security", "This error was generated by Mod_Security"},
		Status:  []int{406, 501},
	},
	{
		Name: "Nginx (WAF / Rate limit)",
		Headers: map[string]string{
			"x-nginx-cache": "",
			"x-nf-request-id": "",
		},
		Body:    []string{"nginx", "openresty", "Access denied by naxsi"},
		Status:  []int{444},
	},
	{
		Name: "Barracuda WAF",
		Headers: map[string]string{
			"x-barracuda-connect": "",
			"server":              "barracuda",
		},
		Body:    []string{"barracuda", "Barracuda Networks", "barra_counter_session"},
		Cookies: []string{"barra_counter_session", "BNI__BARRACUDA_LB_COOKIE"},
	},
	{
		Name: "F5 BIG-IP ASM",
		Headers: map[string]string{
			"x-cnection": "close",
			"server":     "bigip",
		},
		Body:    []string{"BigIP", "F5 Networks", "The requested URL was rejected"},
		Cookies: []string{"TS", "BIGipServer"},
	},
	{
		Name: "Fortinet FortiWeb",
		Headers: map[string]string{
			"x-requestid": "",
		},
		Body:    []string{"FortiWeb", "Fortigate", "FortiGuard", "Application Is Not Available"},
		Cookies: []string{"FORTIWAFSID"},
	},
	{
		Name: "Wordfence (WordPress)",
		Headers: map[string]string{},
		Body:    []string{"Wordfence", "wordfence", "Generated by Wordfence", "This response was generated by Wordfence"},
		Cookies: []string{"wfvt_", "wordfence_verifiedHuman"},
	},
	{
		Name: "SiteLock",
		Headers: map[string]string{
			"x-sitelock-request-id": "",
		},
		Body:    []string{"SiteLock", "sitelock-site-verification"},
		Cookies: []string{"sitelock-shield"},
	},
	{
		Name: "Fastly",
		Headers: map[string]string{
			"x-fastly-request-id": "",
			"fastly-restarts":     "",
			"x-served-by":         "cache-",
			"x-cache":             "HIT",
		},
		Body:    []string{"Fastly error", "fastly"},
		Cookies: []string{},
	},
	{
		Name: "Varnish Cache",
		Headers: map[string]string{
			"x-varnish":        "",
			"via":              "varnish",
			"x-varnish-cache":  "",
		},
		Body:    []string{"varnish", "Error 503"},
	},
	{
		Name: "Reblaze",
		Headers: map[string]string{
			"x-reblaze-protection": "",
		},
		Body:    []string{"Reblaze", "reblaze"},
		Cookies: []string{"rbzid", "x-reblaze-protection"},
	},
	{
		Name: "Edgecast / Verizon",
		Headers: map[string]string{
			"x-ec-custom-error": "",
			"server":            "ECS",
		},
		Body: []string{"Edgecast", "Verizon Digital Media"},
	},
	{
		Name: "Wallarm",
		Headers: map[string]string{
			"x-wallarm-node": "",
		},
		Body:    []string{"wallarm", "Wallarm"},
		Cookies: []string{"wallarm"},
	},
	{
		Name: "DDoS-Guard",
		Headers: map[string]string{
			"server": "ddos-guard",
		},
		Body:    []string{"DDoS-Guard", "ddos-guard"},
		Cookies: []string{"__ddg1", "__ddg2", "__ddgid"},
	},
	{
		Name: "Tencent Cloud WAF",
		Headers: map[string]string{
			"x-from-qq-cloud": "",
		},
		Body:    []string{"waf.tencent", "Tencent Cloud"},
		Cookies: []string{"tencentcloud_waf"},
	},
}

// attackPayloads used to trigger WAF responses
var attackPayloads = []string{
	"/?id=1' OR '1'='1",
	"/?q=<script>alert(1)</script>",
	"/?file=../../etc/passwd",
	"/?cmd=cat+/etc/passwd",
}

func newClient() *http.Client {
	return &http.Client{
		Timeout: 8 * time.Second,
		Transport: &http.Transport{
			TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
		},
		CheckRedirect: func(req *http.Request, via []*http.Request) error {
			return http.ErrUseLastResponse
		},
	}
}

func fetch(client *http.Client, url string) (int, http.Header, string) {
	req, err := http.NewRequest("GET", url, nil)
	if err != nil { return 0, nil, "" }
	req.Header.Set("User-Agent", "Mozilla/5.0 (X11; Linux x86_64) Shinigami/2.0")

	resp, err := client.Do(req)
	if err != nil { return 0, nil, "" }
	defer resp.Body.Close()

	b, _ := io.ReadAll(io.LimitReader(resp.Body, 512*1024))
	return resp.StatusCode, resp.Header, string(b)
}

// Detect runs WAF detection against a target URL
func Detect(targetURL string) *Result {
	printSection("WAF DETECTION  「ファイアウォール検出」")
	fmt.Printf("  %s[*]%s Target: %s%s%s\n\n", C, RST, BLD, targetURL, RST)

	client := newClient()
	result := &Result{}

	// Step 1 — Normal request fingerprint
	fmt.Printf("  %s[~]%s Normal request...\n", C, RST)
	sc, headers, body := fetch(client, targetURL)
	if sc == 0 {
		fmt.Printf("  %s[-]%s Could not reach target\n\n", R, RST)
		return result
	}
	fmt.Printf("  %s[*]%s Status: %s%d%s\n", C, RST, Y, sc, RST)

	// Step 2 — Check headers + body + cookies
	for _, sig := range signatures {
		var evidence []string

		// Header check
		for hName, hVal := range sig.Headers {
			hLower := strings.ToLower(hName)
			for k, vals := range headers {
				if strings.ToLower(k) == hLower {
					v := strings.ToLower(strings.Join(vals, " "))
					if hVal == "" || strings.Contains(v, strings.ToLower(hVal)) {
						evidence = append(evidence, fmt.Sprintf("header: %s: %s", k, strings.Join(vals, ", ")))
					}
				}
			}
		}

		// Cookie check
		for _, cookieName := range sig.Cookies {
			for k, vals := range headers {
				if strings.ToLower(k) == "set-cookie" {
					for _, v := range vals {
						if strings.Contains(strings.ToLower(v), strings.ToLower(cookieName)) {
							evidence = append(evidence, fmt.Sprintf("cookie: %s", v[:min(len(v), 60)]))
						}
					}
				}
			}
		}

		// Body check
		bodyLower := strings.ToLower(body)
		for _, kw := range sig.Body {
			if strings.Contains(bodyLower, strings.ToLower(kw)) {
				evidence = append(evidence, fmt.Sprintf("body: \"%s\"", kw))
			}
		}

		if len(evidence) > 0 {
			result.Detected = true
			result.Name     = sig.Name
			result.Evidence = evidence
			break
		}
	}

	// Step 3 — Attack probe (if not already detected)
	if !result.Detected {
		fmt.Printf("  %s[~]%s Sending attack probes...\n", C, RST)
		for _, payload := range attackPayloads {
			probeURL := strings.TrimRight(targetURL, "/") + payload
			psc, pHeaders, pBody := fetch(client, probeURL)
			pBodyLower := strings.ToLower(pBody)

			for _, sig := range signatures {
				var evidence []string

				// Status check on attack
				for _, expectedSC := range sig.Status {
					if psc == expectedSC {
						evidence = append(evidence, fmt.Sprintf("status %d on attack payload", psc))
					}
				}

				// Header check on attack response
				for hName, hVal := range sig.Headers {
					for k, vals := range pHeaders {
						if strings.ToLower(k) == strings.ToLower(hName) {
							v := strings.ToLower(strings.Join(vals, " "))
							if hVal == "" || strings.Contains(v, strings.ToLower(hVal)) {
								evidence = append(evidence, fmt.Sprintf("header on attack: %s", k))
							}
						}
					}
				}

				// Body check on attack response
				for _, kw := range sig.Body {
					if strings.Contains(pBodyLower, strings.ToLower(kw)) {
						evidence = append(evidence, fmt.Sprintf("blocked body: \"%s\"", kw))
					}
				}

				// Generic block patterns
				blockWords := []string{
					"access denied", "blocked", "forbidden",
					"security", "firewall", "protection",
					"request rejected", "suspicious",
					"illegal", "attack", "threat detected",
				}
				blocked := 0
				for _, bw := range blockWords {
					if strings.Contains(pBodyLower, bw) { blocked++ }
				}
				if blocked >= 2 && !result.Detected {
					evidence = append(evidence, fmt.Sprintf("generic block pattern (%d keywords matched)", blocked))
				}

				if len(evidence) > 0 && !result.Detected {
					result.Detected = true
					result.Name     = sig.Name
					result.Evidence = evidence
					break
				}
			}

			// Generic WAF detect — status code change
			if !result.Detected && psc == 403 && sc != 403 {
				result.Detected = true
				result.Name     = "Unknown WAF"
				result.Evidence = []string{
					fmt.Sprintf("normal=%d, attack probe=%d (possible WAF blocking)", sc, psc),
				}
			}

			if result.Detected { break }
		}
	}

	// Print result
	fmt.Println()
	if result.Detected {
		fmt.Printf("  %s%s╔══════════════════════════════════════════════╗%s\n", BLD, R, RST)
		fmt.Printf("  %s%s║  🔥 WAF DETECTED: %-27s║%s\n", BLD, R, result.Name, RST)
		fmt.Printf("  %s%s╚══════════════════════════════════════════════╝%s\n\n", BLD, R, RST)

		fmt.Printf("  %sEvidence:%s\n", BLD+Y, RST)
		for _, e := range result.Evidence {
			if len(e) > 80 { e = e[:80] + "..." }
			fmt.Printf("    %s→%s %s%s%s\n", C, RST, DIM, e, RST)
		}
		fmt.Println()

		// Bypass tips
		fmt.Printf("  %sBypass Tips for %s:%s\n", BLD+M, result.Name, RST)
		printBypassTips(result.Name)
	} else {
		fmt.Printf("  %s╔══════════════════════════════════════════════╗%s\n", G, RST)
		fmt.Printf("  %s║  ✅ No WAF detected                          ║%s\n", G, RST)
		fmt.Printf("  %s╚══════════════════════════════════════════════╝%s\n\n", G, RST)
	}

	return result
}

func printBypassTips(wafName string) {
	tips := map[string][]string{
		"Cloudflare": {
			"Try origin IP directly (bypass CDN)",
			"Use HTTP/1.0 requests",
			"Add header: X-Forwarded-For: 127.0.0.1",
			"Try subdomain enumeration for unprotected subdomains",
			"Check historical DNS records (Shodan, Censys)",
		},
		"AWS WAF / CloudFront": {
			"Find S3 bucket or origin IP via DNS history",
			"Try X-Forwarded-For header manipulation",
			"Check for exposed API endpoints",
			"Use slow request techniques",
		},
		"ModSecurity": {
			"Try Unicode encoding in payloads",
			"Use HTTP Parameter Pollution",
			"Try multipart/form-data bypass",
			"Double URL encoding",
			"Comment injection in SQL: /*!SELECT*/",
		},
		"Wordfence (WordPress)": {
			"Try /wp-json/wp/v2/ REST API",
			"Use xmlrpc.php if not blocked",
			"Try author enumeration: /?author=1",
			"Check for unprotected wp-cron.php",
		},
		"Imperva / Incapsula": {
			"Try request fragmentation",
			"Use different Content-Type headers",
			"Try IPv6 if available",
			"Check for origin IP in SSL certificate (Censys)",
		},
	}

	wafTips, ok := tips[wafName]
	if !ok {
		wafTips = []string{
			"Try direct origin IP if CDN is used",
			"Use X-Forwarded-For: 127.0.0.1 header",
			"Try Unicode/URL encoding on payloads",
			"Check historical DNS for origin IP",
			"Try HTTP/1.0 instead of HTTP/1.1",
			"Fragment requests to avoid pattern matching",
		}
	}

	for _, tip := range wafTips {
		fmt.Printf("    %s•%s %s\n", Y, RST, tip)
	}
	fmt.Println()
}

func printSection(title string) {
	line := strings.Repeat("═", 56)
	fmt.Printf("\n%s╔%s╗%s\n", M, line, RST)
	fmt.Printf("%s║%s  %s%-54s%s%s║%s\n", M, RST, BLD+W, title, RST, M, RST)
	fmt.Printf("%s╚%s╝%s\n\n", M, line, RST)
}

func min(a, b int) int {
	if a < b { return a }
	return b
}
